export const FORMULARIO_MODULO  = 'FORMULARIO_MODULO';
export const OBTENER_MODULOS    = 'OBTENER_MODULOS';
export const AGREGAR_MODULO     = 'AGREGAR_MODULO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const MODULO_ACTUAL      = 'MODULO_ACTUAL';
export const ELIMINAR_MODULO    = 'ELIMINAR_MODULO';

export const SECCIONES_MODULO   = 'SECCIONES_MODULO';
export const AGREGAR_SECCION    = 'AGREGAR_SECCION';
export const VALIDAR_SECCION    = 'VALIDAR_SECCION';
export const ELIMINAR_SECCION   = 'ELIMINAR_SECCION';
export const ESTADO_SECCION     = 'ESTADO_SECCION';
export const SECCION_ACTUAL     = 'SECCION_ACTUAL';
export const ACTUALIZAR_SECCION = 'ACTUALIZAR_SECCION';
export const LIMPIAR_SECCION    = 'LIMPIAR_SECCION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR   = 'REGISTRO_ERROR';
export const OBTENER_USUARIO  = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO    = 'LOGIN_EXITOSO';
export const LOGIN_ERROR      = 'LOGIN_ERROR';
export const CERRAR_SESION    = 'CERRAR_SESION';

export const VALIDAR_AJUSTES  = 'VALIDAR_AJUSTES';
export const MOSTRAR_OPCION  = 'MOSTRAR_OPCION';

export const ESTADO_NUEVO_USUARIO = 'ESTADO_NUEVO_USUARIO';

export const OBTENER_USUARIOS = "OBTENER_USUARIOS";

export const OBTENER_TEMPLATES = "OBTENER_TEMPLATES";

export const OBTENER_FORMATOS = "OBTENER_FORMATOS";
export const SELECCIONAR_FORMATO = "SELECCIONAR_FORMATO";

export const OBTENER_ZONAS = "OBTENER_ZONAS";

export const OBTENER_ITEMS = "OBTENER_ITEMS";
export const MOSTRAR_ITEM = "MOSTRAR_ITEM";
export const OBTENER_VISTAS_ITEMS = "OBTENER_VISTAS_ITEMS";

export const OBTENER_PROPIEDADES = "OBTENER_PROPIEDADES";

// FormItems
export const OBTENER_ITEMS_FORM = "OBTENER_ITEMS_FORM";
export const GUARDAR_ITEMS_FORM = "GUARDAR_ITEMS_FORM";

// Forms
export const OBTENER_FORMS = "OBTENER_FORMS";
export const GUARDAR_FORMS = "GUARDAR_FORMS";
export const SELECT_FORM = "SELECT_FORM";

// Clientes
export const GUARDAR_CLIENTE = "GUARDAR_CLIENTE";
export const OBTENER_CLIENTES = "OBTENER_CLIENTES";
export const OBTENER_CLIENTE = "OBTENER_CLIENTE";

// Inspector
export const GUARDAR_INSPECTOR = "GUARDAR_INSPECTOR";
export const OBTENER_INSPECTOR = "OBTENER_INSPECTOR";
export const OBTENER_INSPECTORES = "OBTENER_INSPECTORES";

// Archivos S3
export const ARCHIVOS_SUBIR   = 'SUBIR_ARCHiVOS';
export const ARCHIVOS_SUBIDOS = 'ARCHIVOS_SUBIDOS';
export const ARCHIVOS_ERROR   = 'ARCHIVOS_ERROR';
export const ARCHIVOS_CARGADOS= 'ARCHIVOS_CARGADOS';
export const ARCHIVOS_ITEMS_SUBIDOS= 'ARCHIVOS_ITEMS_SUBIDOS';

